---
title: "DDS Final Project"
author: "Helene Barrera"
date: "12/5/2020"
output: html_document
---

library(tidyverse)
library(ggplot2)
library(caret)
library(randomForest)
library(varImp)
library(dplyr)
library(olsrr)
library(questionr)
library(ggcorrplot)
library(jsonlite)
library(class)
library(caret)
library(e1071)
library(GGally)
library(ggthemes)

data = read.csv("D:/MS in Data Science/Datasets/CaseStudy2.csv", header = T)
noAttrition = read.csv("D:/MS in Data Science/Doing Data Science/DDS Final Project/CaseStudy2CompSet No Attrition.csv", header = T)
noSalary = read.csv("D:/MS in Data Science/Doing Data Science/DDS Final Project/CaseStudy2CompSet No Salary.csv", header = T)

data = as.data.frame(data)
noAttrition = as.data.frame(noAttrition)
noSalary = as.data.frame(noSalary)


#Categorize any characters as factors, check for NAs
data <- data %>% mutate_if(is.character,as.factor)
data <- data %>% mutate_if(is.integer, as.numeric)

noAttrition <- noAttrition %>% mutate_if(is.character,as.factor)
noAttrition <- noAttrition %>% mutate_if(is.integer, as.numeric)

noSalary <- noSalary %>% mutate_if(is.character,as.factor)
noSalary <- noSalary %>% mutate_if(is.integer, as.numeric)

str(data)
freq.na(data)
class(data)
sum(is.na(data))

#Remove variables that are all the same: Over18, StandardHours, and EmployeeCount
data2 = select(data, -Over18, -StandardHours, -EmployeeCount)

#Look at numeric variable correlations
#Monthly Income is correlated to many other variables. 
numericdata <- dplyr::select_if(data2, is.numeric)
str(numericdata)
correlations <- cor(numericdata, use = "complete.obs")
correlations <- round(correlations, 2)
ggcorrplot(correlations, type = "upper", lab = F)




#Naive Bayes model 1
##Split into training and test sets
set.seed(123)
splitPerc = .7
trainInd = sample(1:dim(data2)[1], round(splitPerc*dim(data2)[1]))
train = data2[trainInd,]
test = data2[-trainInd,]

##Acc: .7356    Sensitivity: .7751      Specificity: .5769
x <- naiveBayes(Attrition ~ ., data = train, laplace = 1)
x
predictions <- predict(x, test[,names(test) != "Attrition"])
cfm <- confusionMatrix(predictions, test$Attrition)
cfm

#Naive Bayes Model 2 (Removing certain covariates)
##Split into training and test sets
data3 = select(data2, -JobLevel, -YearsWithCurrManager, -YearsSinceLastPromotion)
set.seed(123)
splitPerc = .7
trainInd2 = sample(1:dim(data3)[1], round(splitPerc*dim(data3)[1]))
train2 = data3[trainInd,]
test2 = data3[-trainInd,]

##Acc: .8199    Sensitivity: .8852      Specificity: .5577
x2 <- naiveBayes(Attrition ~ ., data = train2, laplace = 1)
x2
predictions2 <- predict(x2, test2[,names(test2) != "Attrition"])
cfm2 <- confusionMatrix(predictions2, test2$Attrition)
cfm2

#Predict values for the final test data
finalpredict <- predict(x2, noAttrition)
noAttrition$Predictions <- finalpredict
attritionPredictions <- select(noAttrition, ID, Predictions)
write.csv(attritionPredictions, "D:/MS in Data Science/Doing Data Science/DDS Final Project/Case2PredictionsBarrera Attrition.csv", row.names = F)


#Spliting the data for part2
set.seed(123)
splitPerc = .7
trainInd = sample(1:dim(data2)[1], round(splitPerc*dim(data2)[1]))
train = data2[trainInd,]
test = data2[-trainInd,]

#LM 1, Forward, for Monthly Income 
#Adj_Rsq: 0.9472    AIC: 14598.3432    RMSE: 1056.1120    Variables: 4
datalm = lm(MonthlyIncome ~ ., data = data2)
model1 = ols_step_forward_p(datalm, penter=.05, details=T)
model1

model1lm = lm(MonthlyIncome ~ JobLevel + JobRole + TotalWorkingYears + BusinessTravel, data = data2)

noSalary$Predictions <- predict(model1lm, noSalary)
salaryPredictions <- select(noSalary, ID, Predictions)
write.csv(salaryPredictions, "D:/MS in Data Science/Doing Data Science/DDS Final Project/Case2PredictionsBarrera Salary.csv", row.names = F)


#LM 2, Backwards, for Monthly Income 
##Adj_Rsq: 0.948    AIC: 14593    RMSE: 1045.208    Variables: 19
datalm = lm(MonthlyIncome ~ ., data = data2)
model2 = ols_step_backward_p(datalm, penter=.05, details=T)

model2lm = lm(MonthlyIncome ~ BusinessTravel + DailyRate + Department + Gender + JobLevel + JobRole + MonthlyRate + PercentSalaryHike + PerformanceRating + TotalWorkingYears + YearsSinceLastPromotion + YearsWithCurrManager, data = data2)

AIC(model2lm)

#LM 3, Stepwise, for Monthly Income
##Adj_Rsq: 0.948    AIC: 14595    RMSE: 1052.279    Variables: 7
datalm = lm(MonthlyIncome ~ ., data = data2)
model3 = ols_step_both_p(datalm, penter=.05, details=T)

model3lm = lm(MonthlyIncome ~ JobLevel + JobRole + TotalWorkingYears + BusinessTravel + Gender + DailyRate + MonthlyRate, data = data2)

AIC(model3lm)


#LM 6, custom model based on backwards
##Adj_Rsq: 0.947    AIC: 14598.34   RMSE: 1056.112     Variables: 4
finalmodellm = lm(MonthlyIncome ~ JobLevel + JobRole + TotalWorkingYears + BusinessTravel, data = data2)
finalmodel = ols_step_backward_p(finalmodellm, penter=.05, details=T)

AIC(finalmodellm)


#View related data
data2 %>% ggplot(aes(x=MonthlyIncome, y=JobLevel)) + geom_point() + 
          ggtitle("Monthly Income by Job Level")  + theme_economist() 
          
data2 %>% ggplot(aes(x=MonthlyIncome, y=JobRole)) + geom_boxplot() +
          ggtitle("Monthly Income by Job Role") + theme_economist() 
          
data2 %>% ggplot(aes(x=MonthlyIncome, y=TotalWorkingYears)) + geom_point() +
          ggtitle("Monthly Income by Total Working Years") + theme_economist() 
                    
data2 %>% ggplot(aes(x=MonthlyIncome, y=BusinessTravel)) + geom_boxplot() +
          ggtitle("Monthly Income by Business Travel") + theme_economist() 

data2 %>% ggplot(aes(x=JobLevel, y=JobRole)) + geom_boxplot() +
          ggtitle("Job Level vs Job Role") + theme_economist() 


#Predict salaries
finalpredict2 <- predict(finalmodellm, noSalary)
noSalary$Predictions <- finalpredict2      
salaryPredictions <- select(noSalary, ID, Predictions)      
write.csv(salaryPredictions, "D:/MS in Data Science/Doing Data Science/DDS Final Project/Case2PredictionsBarrera Salary.csv", row.names = F)            
